version: '3.8'

services:
  service1:
    build:
      context: ./service1
    container_name: service1
    ports:
      - "3001:3001"
    environment:
      - SERVICE_NAME=Service 1

  service2:
    build:
      context: ./service2
    container_name: service2
    ports:
      - "3002:3002"
    environment:
      - SERVICE_NAME=Service 2

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
      - service2
